
project:
  type: website

website:
  title: "منصة سند للدعم المدرسي"
  navbar:
    right:
      - text: "الرئيسية"
        href: index.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
